[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.19.1"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "v1.6.3"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "v0.11.5"

[[constraint]]
  name = "github.com/hashicorp/hcl"
  revision = "65a6292f0157eff210d03ed1bf6c59b190b8b906"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/pkg/errors"
  revision = "059132a15dd08d6704c67711dae0cf35ab991756"
